Update device traits to not display all serialport capable devices
NordicSemiconductor/pc-nrfconnect-ppk pull request #257
Opened 2022-02-23 08:52 UTC by nicolai-nordic

2022-02-23 10:06 UTC, jonasem approved these changes

2022-02-28 11:29 UTC, datenreisender requested changes

2022-02-28 11:29 UTC, datenreisender commented on Changelog.md
> +- Update device traits to show PPK devices, but not all serialport capable devices.
Users don't know about “device traits”, so lets rephrase to something they can understand better. Suggestion:
```suggestion
-   Hide some non-PPK devices in the device list (we are not yet able to limit
    it to strictly only PPK devices).
```

2022-04-21 06:47 UTC, aadnekar commented
@datenreisender should we go a head and get this into master? We can just commit your suggestion and resolve the conflict with Changelog.md

2023-01-23 09:23 UTC, closed without merging