Feat/select triggering edge
NordicSemiconductor/pc-nrfconnect-ppk pull request #481
Opened 2024-11-04 08:22 UTC by tsvetelinpetrov

2025-02-04 08:56 UTC, kylebonnici approved these changes
Looks good to me upload some screen shots and share with @ketile so we can merge this is :) 

Also do not forget to add the change log (for release date you can right UNRELSED for now) entry and update the version in the package.json :)

2025-02-04 08:56 UTC, kylebonnici commented on src/actions/deviceActions.ts
> +
Consider it to make it a bit more readable 
```suggestion
if (isRaisingEdge){
 validTriggerValue = prevCappedValue != null && prevCappedValue < state.app.trigger.level &&
                         cappedValue >= state.app.trigger.level
}else if (isLoweringEdge){
   validTriggerValue = prevCappedValue != null && prevCappedValue > state.app.trigger.level &&
                             cappedValue <= state.app.trigger.level)
}
                    ((isRaisingEdge &&
                        prevCappedValue < state.app.trigger.level &&
                        cappedValue >= state.app.trigger.level) ||
                        (isLoweringEdge &&
                            prevCappedValue > state.app.trigger.level &&
                            cappedValue <= state.app.trigger.level));

```

2025-02-04 08:56 UTC, kylebonnici commented on src/utils/persistentStore.ts
> +import { type TriggerEdge, type TriggerType } from '../slices/triggerSlice';
Alternative
```suggestion
import type {  TriggerEdge, TriggerType } from '../slices/triggerSlice';
```

2025-02-04 14:27 UTC, tsvetelinpetrov commented
@ketile 
![image](https://github.com/user-attachments/assets/974b23ef-8012-4396-8ecd-5365e03df5f3)

![image](https://github.com/user-attachments/assets/9313acac-7494-44b0-aaa0-cfeab10535be)

2025-03-25 12:33 UTC, tsvetelinpetrov commented
Preview of all changes in the left UI panel:
![image](https://github.com/user-attachments/assets/fec217cb-28c3-486c-bb24-64e86fce7710)

A new feature for defining "Offset" is implemented. Offset is basically the length of pre-trigger data which will be recorded before the trigger is fired. E.g: If the "Offset" = 500ms and "Length" = 1000ms -> total sample length = 1500ms (500ms before trigger and 1000ms after trigger)
![image](https://github.com/user-attachments/assets/ae9b3adf-05ab-47ae-a872-f3239fc815b1)


For analog triggers, use can now choose if the trigger should appear on Rising or Falling edge:
![image](https://github.com/user-attachments/assets/fd67e92d-013c-4d3c-bb38-ef387973623b)
![image](https://github.com/user-attachments/assets/1ab1d7ef-09b3-417d-a483-46bac58379a8)

A new feature for digital triggers is added. User can define the requirements for statuses of the digital channels for when the trigger to be fired.
![image](https://github.com/user-attachments/assets/55dadd41-f551-427b-807d-f5e85c80d9a6)

- **Logic for OR:** Check if the current state is different than previous. If so, check if at least one of the criteria is met -> fire trigger.
- **Logic for AND:** When evaluating the triggering conditions, first we check if the new logic state is different from the previous one. If it is different, evaluate all triggering conditions. If the conditions are met -> fire the trigger.

2025-03-27 12:01 UTC, greg-fer requested changes
Poke me back after you have discussed edits with @ketile . We will then update the docs.

2025-03-27 12:01 UTC, greg-fer commented on src/components/SidePanel/SamplingSettings.tsx
> +                title="Duration of the pre-trigger data"
"duration of data" is contradictory: data is or isn't. Do you mean how long the data is meant to be stored?

2025-03-27 12:09 UTC, tsvetelinpetrov commented on src/components/SidePanel/SamplingSettings.tsx
> +                title="Duration of the pre-trigger data"
Or we can use the text from changelog: "Pre-trigger data length to be recorded before the trigger".

2025-03-28 07:36 UTC, greg-fer commented on src/components/SidePanel/SamplingSettings.tsx
> +                title="Duration of the pre-trigger data"
I like "Duration of the pre-trigger data sampling"

2025-07-22 10:21 UTC, merged

2025-07-28 08:42 UTC, greg-fer commented
Kindly please do not merge PRs like this. I clearly mentioned doc updates are needed in March and blocked the PR on purpose. I have waited for information so that I could update the docs IN THIS PR. And all of a sudden, the PR is merged.